More changes

diff --git a/.github/workflows/09-function.yaml b/.github/workflows/09-function.yaml
--- a/.github/workflows/09-function.yaml
+++ b/.github/workflows/09-function.yaml
@@ -14,11 +14,11 @@ jobs:
     steps:
       - name: Sleep for 20 seconds
         run: sleep 20
-      - name: Failing step
-        run: exit 1
+      # - name: Failing step
+      #   run: exit 1
       - name: I will be skipped
         if: ${{ success() }}
-        run: echo "I will print if previous steps succeed."
+        run: echo "I will print if previous steps succeed."; exit 0
       - name: I will execute
         if: ${{ failure() }}
         run: echo "I will print if any previous step fails."
